version: '3.8'

services:
  oracle:
    image: container-registry.oracle.com/database/express:latest
    container_name: timeforing-oracle
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=TimeForing123!
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "timeforing_user/TimeTrack123@localhost:1521/XEPDB1", "<<<", "SELECT 1 FROM dual;"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  oracle-data:
