spring:
  application:
    name: base-springboot-api-kotlin
  
  profiles:
    active: dev
  
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XEPDB1
    username: ${DB_USERNAME:dev_user}
    password: ${DB_PASSWORD:dev_password}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    schemas: ${DB_SCHEMA:DEV_SCHEMA}
    validate-on-migrate: true
    clean-disabled: true
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:https://your-oauth2-provider.com}
          audiences: ${JWT_AUDIENCES:api}

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
  forward-headers-strategy: native

# Management/Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# Logging
logging:
  level:
    com.example: INFO
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.flywaydb: INFO
  pattern:
    console: "%d{ISO8601} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{ISO8601} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log

# SpringDoc OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  show-actuator: false

# Application specific properties
app:
  name: "Base Spring Boot API"
  version: "@project.version@"
  description: "Base Spring Boot API template in Kotlin"
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XEPDB1
    username: ${DB_USERNAME:dev_user}
    password: ${DB_PASSWORD:dev_password}
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:https://dev-oauth2-provider.com}

logging:
  level:
    com.example: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.springframework.security: DEBUG

---
# Test Profile
spring:
  config:
    activate:
      on-profile: test
  
  datasource:
    url: jdbc:tc:oracle:thin:@//test-oracle:1521/xe
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  
  flyway:
    clean-disabled: false
    
logging:
  level:
    com.example: DEBUG
    org.testcontainers: INFO

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}

logging:
  level:
    com.example: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
  file:
    name: /var/log/app/application.log