# Docker-specific configuration
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=oracledb)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=XEPDB1)))}
    username: ${SPRING_DATASOURCE_USERNAME:timeforing_user}
    password: ${SPRING_DATASOURCE_PASSWORD:TimeTrack123}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  # Flyway configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true
    validate-on-migrate: true

  # Security configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8081/auth/realms/timeforing}

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /

# Logging configuration for Docker
logging:
  level:
    com.example.basespringbootapikotlin: INFO
    org.springframework.security: DEBUG
    org.springframework.jdbc: DEBUG
    com.zaxxer.hikari: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: /app/logs/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# Application info
info:
  app:
    name: Timeforing API
    description: Time tracking application API
    version: 1.0.0
    profile: docker
