-- Create users table with Norwegian field names as per requirements
-- Includes: id, navn, mobil, epost, opprettet_dato, sist_endret
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    navn VARCHAR2(255),
    mobil VARCHAR2(20),
    epost VARCHAR2(255) NOT NULL,
    status VARCHAR2(50) DEFAULT 'ACTIVE' NOT NULL,
    opprettet_dato TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    sist_endret TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version NUMBER DEFAULT 1 NOT NULL,
    
    CONSTRAINT uk_users_epost UNIQUE (epost),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'PENDING', 'SUSPENDED')),
    CONSTRAINT ck_users_mobil_format CHECK (mobil IS NULL OR REGEXP_LIKE(mobil, '^(\+47)?[0-9]{8}$'))
);

-- Create indexes for performance
-- Note: idx_users_epost is automatically created by the UNIQUE constraint
CREATE INDEX idx_users_navn ON users(navn);
CREATE INDEX idx_users_status ON users(status);
CREATE INDEX idx_users_opprettet_dato ON users(opprettet_dato);

-- Create sequence for manual ID generation if needed
CREATE SEQUENCE users_seq START WITH 1000 INCREMENT BY 1;

-- Add comments for documentation
COMMENT ON TABLE users IS 'Brukerkontoer og profiler';
COMMENT ON COLUMN users.user_id IS 'Primærnøkkel - unik bruker identifikator';
COMMENT ON COLUMN users.navn IS 'Brukerens fulle navn';
COMMENT ON COLUMN users.mobil IS 'Brukerens mobilnummer (norsk format)';
COMMENT ON COLUMN users.epost IS 'Brukerens e-postadresse - må være unik';
COMMENT ON COLUMN users.status IS 'Brukerkonto status';
COMMENT ON COLUMN users.opprettet_dato IS 'Tidspunkt når bruker ble opprettet';
COMMENT ON COLUMN users.sist_endret IS 'Tidspunkt når bruker sist ble endret';
COMMENT ON COLUMN users.version IS 'Optimistic locking versjon';

-- Create trigger for automatic sist_endret (last modified)
CREATE OR REPLACE TRIGGER trg_users_sist_endret
    BEFORE UPDATE ON users
    FOR EACH ROW
BEGIN
    :NEW.sist_endret := CURRENT_TIMESTAMP;
    :NEW.version := :OLD.version + 1;
END;
/