-- Create projects table (stateless, no user FK)
CREATE TABLE projects (
    project_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_sub VARCHAR2(128) NOT NULL,
    navn VARCHAR2(100) NOT NULL,
    beskrivelse VARCHAR2(500),
    aktiv NUMBER(1) DEFAULT 1 NOT NULL,
    opprettet_dato TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    endret_dato TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_projects_aktiv CHECK (aktiv IN (0, 1))
);

-- Create indexes for performance
CREATE INDEX idx_projects_user_sub ON projects(user_sub);
CREATE INDEX idx_projects_aktiv ON projects(aktiv);

-- Add comments for documentation
COMMENT ON TABLE projects IS 'Prosjekter for timeføring, stateless (user_sub from JWT)';
COMMENT ON COLUMN projects.project_id IS 'Primærnøkkel - unik prosjekt identifikator';
COMMENT ON COLUMN projects.user_sub IS 'JWT sub claim for user (stateless)';
COMMENT ON COLUMN projects.navn IS 'Prosjektets navn';
COMMENT ON COLUMN projects.beskrivelse IS 'Detaljert beskrivelse av prosjektet';
COMMENT ON COLUMN projects.aktiv IS 'Om prosjektet er aktivt (1) eller inaktivt (0)';
COMMENT ON COLUMN projects.opprettet_dato IS 'Tidspunkt når prosjektet ble opprettet';
COMMENT ON COLUMN projects.endret_dato IS 'Tidspunkt når prosjektet sist ble endret';
