-- Create projects table
-- Contains: id, navn, beskrivelse, aktiv, opprettet_dato, bruker_id

CREATE TABLE projects (
    project_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    navn VARCHAR2(255) NOT NULL,
    beskrivelse CLOB,
    aktiv NUMBER(1) DEFAULT 1 NOT NULL,
    opprettet_dato TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    sist_endret TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    bruker_id NUMBER NOT NULL,
    version NUMBER DEFAULT 1 NOT NULL,
    
    -- Foreign key constraint to users table
    CONSTRAINT fk_projects_bruker_id FOREIGN KEY (bruker_id) REFERENCES users(user_id),
    
    -- Check constraint for aktiv field (1 = active, 0 = inactive)
    CONSTRAINT ck_projects_aktiv CHECK (aktiv IN (0, 1))
);

-- Create indexes for performance
CREATE INDEX idx_projects_navn ON projects(navn);
CREATE INDEX idx_projects_aktiv ON projects(aktiv);
CREATE INDEX idx_projects_bruker_id ON projects(bruker_id);
CREATE INDEX idx_projects_opprettet_dato ON projects(opprettet_dato);

-- Create sequence for manual ID generation if needed
CREATE SEQUENCE projects_seq START WITH 1000 INCREMENT BY 1;

-- Add comments for documentation
COMMENT ON TABLE projects IS 'Prosjekter for timeføring';
COMMENT ON COLUMN projects.project_id IS 'Primærnøkkel - unik prosjekt identifikator';
COMMENT ON COLUMN projects.navn IS 'Prosjektets navn';
COMMENT ON COLUMN projects.beskrivelse IS 'Detaljert beskrivelse av prosjektet';
COMMENT ON COLUMN projects.aktiv IS 'Om prosjektet er aktivt (1) eller inaktivt (0)';
COMMENT ON COLUMN projects.opprettet_dato IS 'Tidspunkt når prosjektet ble opprettet';
COMMENT ON COLUMN projects.sist_endret IS 'Tidspunkt når prosjektet sist ble endret';
COMMENT ON COLUMN projects.bruker_id IS 'Referanse til bruker som eier prosjektet';
COMMENT ON COLUMN projects.version IS 'Optimistic locking versjon';

-- Create trigger for automatic sist_endret (last modified)
CREATE OR REPLACE TRIGGER trg_projects_sist_endret
    BEFORE UPDATE ON projects
    FOR EACH ROW
BEGIN
    :NEW.sist_endret := CURRENT_TIMESTAMP;
    :NEW.version := :OLD.version + 1;
END;
/
