-- Create time_entries table (stateless, no user FK)

CREATE TABLE time_entries (
    time_entry_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prosjekt_id NUMBER NOT NULL,
    user_sub VARCHAR2(128) NOT NULL,
    dato DATE NOT NULL,
    timer NUMBER(4,2) NOT NULL,
    kommentar CLOB,
    opprettet_dato TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    sist_endret TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version NUMBER DEFAULT 1 NOT NULL,
    CONSTRAINT fk_time_entries_prosjekt_id FOREIGN KEY (prosjekt_id) REFERENCES projects(project_id),
    CONSTRAINT ck_time_entries_timer_positive CHECK (timer > 0),
    CONSTRAINT ck_time_entries_timer_max CHECK (timer <= 24),
    CONSTRAINT ck_time_entries_timer_half_or_whole CHECK (MOD(timer * 2, 1) = 0),
    CONSTRAINT uq_time_entries_user_dato UNIQUE (user_sub, dato, prosjekt_id)
);


CREATE INDEX idx_time_entries_prosjekt_id ON time_entries(prosjekt_id);
CREATE INDEX idx_time_entries_user_sub ON time_entries(user_sub);
CREATE INDEX idx_time_entries_dato ON time_entries(dato);
CREATE INDEX idx_time_entries_opprettet_dato ON time_entries(opprettet_dato);
CREATE INDEX idx_time_entries_user_dato ON time_entries(user_sub, dato);
CREATE INDEX idx_time_entries_prosjekt_dato ON time_entries(prosjekt_id, dato);

-- Create sequence for manual ID generation if needed
CREATE SEQUENCE time_entries_seq START WITH 1000 INCREMENT BY 1;


COMMENT ON TABLE time_entries IS 'Timeføringer registrert av brukere på prosjekter (stateless, user_sub from JWT). Kun hele eller halve timer, maks 24 timer per dag per bruker.';
COMMENT ON COLUMN time_entries.time_entry_id IS 'Primærnøkkel - unik timeføring identifikator';
COMMENT ON COLUMN time_entries.prosjekt_id IS 'Referanse til prosjekt timeføringen gjelder';
COMMENT ON COLUMN time_entries.user_sub IS 'JWT sub claim for user (stateless)';
COMMENT ON COLUMN time_entries.dato IS 'Dato for når arbeidet ble utført';
COMMENT ON COLUMN time_entries.timer IS 'Antall timer arbeidet (kun hele eller halve timer, maks 24)';
COMMENT ON COLUMN time_entries.kommentar IS 'Kommentar eller beskrivelse av arbeidet';
COMMENT ON COLUMN time_entries.opprettet_dato IS 'Tidspunkt når timeføringen ble registrert';
COMMENT ON COLUMN time_entries.sist_endret IS 'Tidspunkt når timeføringen sist ble endret';
COMMENT ON COLUMN time_entries.version IS 'Optimistic locking versjon';

-- Create trigger for automatic sist_endret (last modified)
CREATE OR REPLACE TRIGGER trg_time_entries_sist_endret
    BEFORE UPDATE ON time_entries
    FOR EACH ROW
BEGIN
    :NEW.sist_endret := CURRENT_TIMESTAMP;
    :NEW.version := :OLD.version + 1;
END;
/
