-- Create projects table
-- Contains: id, navn, beskrivelse, aktiv, opprettet_dato, bruker_id


CREATE TABLE projects (
    project_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    navn VARCHAR2(100) NOT NULL,
    beskrivelse VARCHAR2(500),
    aktiv NUMBER(1) DEFAULT 1 NOT NULL,
    opprettet_dato TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    endret_dato TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_projects_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT ck_projects_aktiv CHECK (aktiv IN (0, 1))
);

-- Create indexes for performance

CREATE INDEX idx_projects_user ON projects(user_id);
CREATE INDEX idx_projects_aktiv ON projects(aktiv);

-- Create sequence for manual ID generation if needed


-- Add comments for documentation

COMMENT ON TABLE projects IS 'Prosjekter for timeføring';
COMMENT ON COLUMN projects.project_id IS 'Primærnøkkel - unik prosjekt identifikator';
COMMENT ON COLUMN projects.user_id IS 'Referanse til bruker som eier prosjektet';
COMMENT ON COLUMN projects.navn IS 'Prosjektets navn';
COMMENT ON COLUMN projects.beskrivelse IS 'Detaljert beskrivelse av prosjektet';
COMMENT ON COLUMN projects.aktiv IS 'Om prosjektet er aktivt (1) eller inaktivt (0)';
COMMENT ON COLUMN projects.opprettet_dato IS 'Tidspunkt når prosjektet ble opprettet';
COMMENT ON COLUMN projects.endret_dato IS 'Tidspunkt når prosjektet sist ble endret';
