name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Update Maven dependencies
      run: |
        mvn versions:update-properties
        mvn versions:use-latest-releases
    
    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Create Pull Request
      if: steps.changes.outputs.changed == 'true'
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update Maven dependencies'
        title: '🔄 Automated Dependency Updates'
        body: |
          ## Automated Dependency Updates
          
          This PR updates Maven dependencies to their latest versions.
          
          ### Changes
          - Updated Maven properties and dependency versions
          - Generated by GitHub Actions dependency update workflow
          
          ### Testing
          - [ ] All tests pass
          - [ ] No breaking changes introduced
          - [ ] Security vulnerabilities addressed
          
          **Auto-generated by GitHub Actions** 🤖
        branch: chore/update-dependencies
        base: main
        delete-branch: true
